export * as anilistAPI from 'src/api/anilist'
export * as authAPI from 'src/api/auth'
export * as bookAPI from 'src/api/book'
export { FetchError, pageURL } from 'src/api/internal'
export * as seriesAPI from 'src/api/series'
export * as userAPI from 'src/api/user'
export * as userBookAPI from 'src/api/user-book'
export * as userSeriesAPI from 'src/api/user-series'
export * as rumAPI from 'src/api/rum'
