export * as anilist from 'src/api/anilist'
export * as auth from 'src/api/auth'
export * as book from 'src/api/book'
export { FetchError, pageURL } from 'src/api/internal'
export * as series from 'src/api/series'
export * as user from 'src/api/user'
export * as userBook from 'src/api/user-book'
export * as userSeries from 'src/api/user-series'
export * as rum from 'src/api/rum'
