// This file is autogenerated do not edit it
/* eslint-disable */

export interface Book {
    id: string
    title: string
    chapter: number | null
    volume: number | null
    series: string
    authors: Array<string>
    pages: Array<Page>
    sort: string
    cover_url: string
    user_book: UserBook | null
}
export interface Page {
    url: string
    type: 'FrontCover' | 'Story' | 'Deleted'
}
export interface Series {
    name: string
    cover_url: string
    first_book_id: string | null
}
export interface User {
    id: string
    username: string
}
export interface UserBook {
    book_id: string
    user_id: string
    current_page: number | null
}
