// This file is autogenerated do not edit it
/* eslint-disable */

export interface Book {
    created_at: string
    updated_at: string
    deleted_at: string | null
    update_map: Record<string, string>
    id: string
    title: string
    chapter: number | null
    volume: number | null
    series: string
    authors: Array<string>
    pages: Array<Page>
    page_count: number
    rtl: boolean
    sort: string
    file: string
    cover_url: string
    user_book: UserBook | null
}
export interface Page {
    url: string
    type: PageType
}
export interface Series {
    created_at: string
    updated_at: string
    deleted_at: string | null
    update_map: Record<string, string>
    name: string
    cover_url: string
    first_book_id: string | null
    user_series: UserSeries | null
    anilist_id: number | null
}
export interface User {
    created_at: string
    updated_at: string
    deleted_at: string | null
    update_map: Record<string, string>
    id: string
    username: string
}
export interface UserBook {
    created_at: string
    updated_at: string
    deleted_at: string | null
    update_map: Record<string, string>
    current_page: number
}
export interface UserSeries {
    created_at: string
    updated_at: string
    deleted_at: string | null
    update_map: Record<string, string>
    list: List
}
export enum PageType {
    Deleted = "Deleted",
    FrontCover = "FrontCover",
    Spread = "Spread",
    SpreadSplit = "SpreadSplit",
    Story = "Story",
}
export enum List {
    Completed = "completed",
    Dropped = "dropped",
    None = "",
    Paused = "paused",
    Planning = "planning",
    Reading = "reading",
}
